HOME = '/home'
CREATE_PROJECT = '/create-project'
DEFINE_METHOD = '/define-method'
PROJECT_LIST = '/project-list'
PROJECT = '/project/<project_name>'
PROJECT_NO_ID = '/project'
PROJECT_DOWNLOAD = '/project-download/'
RCH_SHAPES = '/rch-shapes/<rch_shape_index>'
UPLOAD_HYDRUS = '/upload-hydrus'
UPLOAD_MODFLOW = '/upload-modflow'
CONFIGURATION = '/configuration'
DEFINE_SHAPES = '/define-shapes/<hydrus_model_index>'
SIMULATION = '/simulation'
SIMULATION_RUN = '/simulation-run'
SIMULATION_CHECK = '/simulation-check/<simulation_id>'

